services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GEMINI_API_KEY=${VITE_CLOUD_TRANSLATION_API_KEY} # maps user key
      - PORT=8080
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - VITE_API_URL=http://localhost:8080/api/v1
    depends_on:
      - backend
    restart: always
